### ISSUE TITLE
Incompatible `kotlin_version` with latest Gradle Plugin

### ISSUE THREAD

**Issue by Amphaal** [alann-maulana/image_compression_flutter#9]
<img width="788" alt="Capture d’écran 2023-05-09 à 19 48 59" src="https://github.com/alann-maulana/image_compression_flutter/assets/13903151/7d1e4b32-752a-4613-b4fe-9ebe2345c9e6">

Seems like the issue was fixed in https://github.com/alann-maulana/image_compression_flutter/commit/6ec0e86d0ba35dd57aa0da49d4ee712d7a7396a4.

@alann-maulana would you push a new version minor / major version of the lib since it could involve breakage ? Many thx

**Comment by alexaniko88** [comment]
Any updates on this issue @alann-maulana?

**Comment by TimeLord2010** [comment]
Same problem here.

**Comment by deevsaini** [comment]
any updates guys?

**Comment by TimeLord2010** [comment]
I solved this at the time by putting this in the dependencies:
```
  image_compression_flutter:
    git: 
      url: https://github.com/alann-maulana/image_compression_flutter.git
      ref: 6ec0e86

```

Are you sure the bug is still there? Its been months.
